server:
  port: 8084

spring:
  application:
    name: entregas-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/entregas_db}
    username: ${SPRING_DATASOURCE_USERNAME:mzlog}
    password: ${SPRING_DATASOURCE_PASSWORD:mzlog}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
