name: CI Multi-Microsservicos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Baixa o código do mzlog-app na máquina virtual
    - name: Copiar codigo do repositorio
      uses: actions/checkout@v4

    # 2. Instala o Java 21 (Versão real do seu projeto!)
    - name: Instalar Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    # 3. Executa a compilação de todos os microsserviços ignorando testes pesados por enquanto
    # O parâmetro -DskipTests garante que o Maven apenas cheque a sintaxe e compile as classes
    - name: Validar API Gateway
      run: |
        cd backend/api-gateway
        mvn clean package -DskipTests

    - name: Validar Auth Service
      run: |
        cd backend/auth-service
        mvn clean package -DskipTests

    - name: Validar Clientes Service
      run: |
        cd backend/clientes-service
        mvn clean package -DskipTests

    - name: Validar Funcionarios Service
      run: |
        cd backend/funcionarios-service
        mvn clean package -DskipTests

    - name: Validar Entregas Service
      run: |
        cd backend/entregas-service
        mvn clean package -DskipTests
