name: CI/CD Multi-Microsservicos com Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Baixa o código do mzlog-app na máquina virtual
    - name: Copiar codigo do repositorio
      uses: actions/checkout@v4

    # 2. Instala o Java 21
    - name: Instalar Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    # 3. Compila todos os microsserviços e gera os arquivos .jar brutos (Fase de CI)
    - name: Compilar Microsservicos (Gerar JARs)
      run: |
        cd backend/api-gateway && mvn clean package -DskipTests
        cd ../auth-service && mvn clean package -DskipTests
        cd ../clientes-service && mvn clean package -DskipTests
        cd ../funcionarios-service && mvn clean package -DskipTests
        cd ../entregas-service && mvn clean package -DskipTests

    # 4. Fase de CD: Constrói as imagens Docker e sobe todos os containers usando o docker-compose
    # O parâmetro -d faz rodar em segundo plano, e o --wait garante que a esteira espere todos os containers ficarem saudáveis
    - name: Construir e Levantar Infraestrutura com Docker Compose
      run: |
        docker compose up --build -d --wait

    # 5. Validação visual dos containers ativos (Para vermos no terminal preto se tudo subiu)
    - name: Listar Containers Ativos
      run: docker ps
